"""
Mapa editorial del blog de soyroman.com (motor v2).

90 temas: 10 por cada una de las 9 categorías del CMS. Cada tema trae lo que el
motor necesita para escribir con criterio y no "sobre" un tema:

  title     tema de trabajo (el título final lo propone el brief)
  cat       slug de la categoría (Temas) en el CMS
  fmt       formato: marco | guia | comparativa | opinion | plantilla | checklist | errores
  reader    para quién se escribe
  intent    qué busca ese lector cuando llega
  thesis    la postura que el artículo defiende (no se negocia en la redacción)
  terms     slugs del glosario que deben enlazarse si aparecen
  resource  slug de /recursos para el llamado a la acción ("" = ninguno)
  pillar    True = artículo pilar (1500-2000 palabras); False = satélite (800-1100)

Orden de cada categoría: el pilar primero, luego de lo más buscado a lo más nicho.
Se excluyen temas ya publicados (Core Web Vitals, eventos B2B).
"""

CAT_EXPERTISE = {
    "generacion-demanda": "generacion-demanda-b2b",
    "crm-revops": "crm-revops",
    "seo-aeo": "seo-aeo-geo",
    "paid-media": "paid-media",
    "contenido-email": "generacion-demanda-b2b",
    "analitica": "crm-revops",
    "sitios-web": "web-herramientas",
    "liderazgo": "liderazgo-equipos",
    "ia-aplicada": "motores-ia",
}

READERS = {
    "cmo": "director o directora de marketing B2B",
    "gm": "gerente de marketing en una empresa B2B en crecimiento",
    "ventas": "director comercial que trabaja con marketing",
    "ceo": "fundador o CEO de una empresa B2B de 20 a 200 personas",
    "ops": "responsable de RevOps u operaciones de marketing",
    "paid": "especialista o líder de paid media B2B",
    "contenido": "líder de contenido o de marketing digital",
}


def T(title, cat, fmt, reader, intent, thesis, terms=(), resource="", pillar=False):
    return {
        "title": title, "cat": cat, "fmt": fmt, "reader": READERS[reader], "intent": intent,
        "thesis": thesis, "terms": list(terms), "resource": resource, "pillar": pillar,
    }


TOPICS = [
    # ───────── Generación de demanda ─────────
    T("Generación de demanda B2B con ciclos largos: del lead al pipeline medible", "generacion-demanda", "marco", "cmo",
      "entender cómo planear demanda cuando la venta tarda meses",
      "En B2B de ciclo largo la demanda se mide en pipeline creado, no en leads; el plan empieza por la meta de ingresos y se calcula hacia atrás.",
      ["pipeline", "mql", "sql", "embudo-de-ventas", "win-rate"], "embudo-inverso", True),
    T("Cómo calcular cuántos leads necesitas para tu meta de ingresos", "generacion-demanda", "guia", "gm",
      "saber cuántos leads pedir y justificar el presupuesto",
      "La meta de leads no se adivina: sale de dividir la meta de ingresos entre el ticket y las tasas reales de cada etapa.",
      ["lead", "mql", "sql", "tasa-de-conversion", "win-rate"], "embudo-inverso"),
    T("MQL y SQL: definiciones que marketing y ventas firman juntos", "generacion-demanda", "plantilla", "ventas",
      "acabar con la discusión de qué es un lead calificado",
      "Un MQL sin criterios escritos y aceptados por ventas es una opinión; la definición debe caber en una página y revisarse cada trimestre.",
      ["mql", "sql", "sal", "sla-marketing-ventas", "lead-scoring"], "embudo-inverso"),
    T("ABM sin herramientas caras: cómo empezar con 50 cuentas", "generacion-demanda", "guia", "gm",
      "probar account-based marketing sin comprar una plataforma",
      "ABM es una forma de priorizar, no un software: con una lista de 50 cuentas, contenido por industria y coordinación con ventas ya se ven resultados.",
      ["abm", "icp", "sdr", "pipeline"]),
    T("Inbound y outbound no compiten: cómo diseñar el mix por etapa del embudo", "generacion-demanda", "marco", "cmo",
      "decidir cuánto invertir en inbound frente a outbound",
      "El mix correcto depende del tamaño del mercado direccionable y del ticket; con pocas cuentas, outbound coordinado con contenido gana.",
      ["inbound-marketing", "outbound", "sdr", "bdr"]),
    T("El handoff de marketing a ventas: dónde se pierden los leads y cómo evitarlo", "generacion-demanda", "errores", "ventas",
      "entender por qué los leads 'buenos' no se convierten",
      "La mayoría de los leads se pierden en las primeras 48 horas por falta de un SLA con tiempos y responsables, no por mala calidad.",
      ["sla-marketing-ventas", "sal", "mql", "lead"]),
    T("Lead magnets B2B que atraen a quien decide, no a estudiantes", "generacion-demanda", "checklist", "contenido",
      "crear un recurso descargable que traiga leads calificados",
      "Un buen lead magnet resuelve un problema operativo concreto del comprador; los ebooks genéricos llenan la base de contactos que nunca compran.",
      ["lead-magnet", "icp", "buyer-persona", "landing-page"], "embudo-inverso"),
    T("Outbound y contenido: cómo un SDR aprovecha lo que publica marketing", "generacion-demanda", "guia", "ventas",
      "hacer que el contenido de marketing ayude a prospectar",
      "El SDR que comparte contenido útil abre más conversaciones que el que pide una llamada; marketing debe producir pensando en esas conversaciones.",
      ["sdr", "outbound", "abm"]),
    T("Webinars B2B que generan pipeline y no solo registros", "generacion-demanda", "errores", "gm",
      "sacarle negocio a los webinars",
      "Un webinar vale por las conversaciones de ventas que provoca después; sin seguimiento en 72 horas, los registros no significan nada.",
      ["nurturing", "mql", "pipeline"]),
    T("Cómo priorizar canales de demanda con presupuesto limitado", "generacion-demanda", "marco", "ceo",
      "decidir dónde poner el primer peso de marketing",
      "Con presupuesto limitado conviene dominar un canal antes de abrir el siguiente; dispersarse en cinco canales impide aprender de cualquiera.",
      ["cac", "pipeline", "roi"], "roas-romi-roi"),

    # ───────── CRM y RevOps ─────────
    T("RevOps para equipos B2B pequeños: alinear marketing, ventas y datos sin un área de operaciones", "crm-revops", "marco", "ceo",
      "entender qué es RevOps y por dónde empezar sin contratar un equipo",
      "RevOps empieza con tres acuerdos: una definición de etapas, un dueño de los datos y un tablero que todos miran; las herramientas vienen después.",
      ["revops", "crm", "pipeline", "forecast", "ciclo-de-vida"], "embudo-inverso", True),
    T("Saneamiento de CRM: de una base caótica a un pipeline en el que se puede confiar", "crm-revops", "guia", "ops",
      "limpiar un CRM desordenado sin perder historial",
      "La limpieza de un CRM es iterativa: primero duplicados y propiedades muertas, luego reglas que impidan que el desorden vuelva.",
      ["crm", "pipeline", "ciclo-de-vida"]),
    T("Etapas de pipeline que reflejan cómo compra el cliente, no cómo vende el equipo", "crm-revops", "marco", "ventas",
      "rediseñar las etapas del pipeline",
      "Cada etapa debe tener un criterio de salida verificable por el comprador; si una etapa depende de la sensación del vendedor, el forecast miente.",
      ["pipeline", "forecast", "meddic", "velocidad-del-pipeline"], "embudo-inverso"),
    T("Por qué cinco pipelines distintos destruyen tu forecast", "crm-revops", "opinion", "cmo",
      "entender por qué no cuadra el forecast",
      "Varios pipelines con criterios distintos hacen imposible sumar oportunidades; unificar en un modelo común vale más que cualquier herramienta de forecast.",
      ["pipeline", "forecast", "meddic"]),
    T("MEDDIC aplicado: cómo usarlo para calificar sin burocracia", "crm-revops", "guia", "ventas",
      "implementar MEDDIC en el CRM",
      "MEDDIC funciona cuando se traduce en 6 propiedades obligatorias por etapa, no cuando se vuelve un formulario de 30 campos.",
      ["meddic", "bant", "pipeline", "win-rate"]),
    T("Lead scoring sin machine learning: un modelo simple que ventas sí usa", "crm-revops", "plantilla", "ops",
      "armar un lead scoring útil desde cero",
      "Un scoring de dos ejes, ajuste al ICP e interés demostrado, explicable en una frase, supera a modelos complejos que nadie entiende.",
      ["lead-scoring", "icp", "mql"]),
    T("Cómo detectar y fusionar duplicados en HubSpot sin romper el historial", "crm-revops", "guia", "ops",
      "limpiar duplicados en HubSpot con seguridad",
      "Fusionar sin reglas de prioridad destruye datos; antes de fusionar se define qué registro y qué propiedad ganan.",
      ["crm"]),
    T("Propiedades de CRM: cuántas son demasiadas y cómo auditarlas", "crm-revops", "checklist", "ops",
      "ordenar un CRM con cientos de propiedades",
      "Una propiedad que nadie llena ni reporta es deuda; la auditoría se hace por uso real, no por opinión.",
      ["crm", "ciclo-de-vida"]),
    T("Migrar de CRM sin perder datos: el plan que sí funciona", "crm-revops", "checklist", "ops",
      "planear una migración de CRM",
      "La migración es la oportunidad de rediseñar el embudo; mover los datos tal cual solo traslada el desorden a una herramienta más cara.",
      ["crm", "ciclo-de-vida", "pipeline"]),
    T("Forecast de ventas B2B: del optimismo del vendedor a un número defendible", "crm-revops", "marco", "cmo",
      "hacer un forecast confiable",
      "Un forecast defendible combina probabilidades por etapa calculadas con histórico y una revisión semanal de negocios estancados.",
      ["forecast", "pipeline", "win-rate", "velocidad-del-pipeline"], "embudo-inverso"),

    # ───────── SEO y AEO ─────────
    T("SEO, AEO y GEO para empresas B2B: que te encuentren buscadores e IAs", "seo-aeo", "marco", "cmo",
      "entender cómo cambia el SEO con los motores de respuesta",
      "El objetivo ya no es solo rankear sino ser la fuente citada; eso exige páginas que respondan preguntas concretas con datos y estructura clara.",
      ["seo", "aeo", "geo", "serp", "schema-markup"], "", True),
    T("Páginas de servicio B2B que responden preguntas: estructura para buscadores y para IAs", "seo-aeo", "plantilla", "gm",
      "reescribir páginas de servicio para que posicionen",
      "Una página de servicio debe responder qué es, para quién, cómo funciona y cuánto tarda; la lista de beneficios genéricos no la cita nadie.",
      ["aeo", "seo", "landing-page", "cta"]),
    T("Schema markup para empresas de servicios B2B: lo mínimo que sí importa", "seo-aeo", "checklist", "gm",
      "saber qué datos estructurados implementar",
      "Organization, Service, FAQ y Article bien hechos cubren el 80 % del valor; marcar todo sin cuidado no ayuda.",
      ["schema-markup", "aeo", "serp"]),
    T("Cómo medir si apareces en ChatGPT, Perplexity y AI Overviews", "seo-aeo", "guia", "cmo",
      "medir la visibilidad en motores de IA",
      "La visibilidad en IA se mide con un set fijo de preguntas de compra revisado cada mes; sin línea base, cualquier mejora es anecdótica.",
      ["aeo", "geo", "share-of-voice"]),
    T("Search Console para equipos de marketing: tres reportes para revisar cada semana", "seo-aeo", "guia", "gm",
      "usar Search Console sin perderse",
      "Tres reportes bastan: consultas en posiciones 5 a 15, páginas que pierden clics y cobertura con errores; lo demás es para auditorías.",
      ["seo", "serp", "ctr"]),
    T("Investigación de keywords B2B cuando el volumen es casi cero", "seo-aeo", "guia", "contenido",
      "encontrar temas cuando las herramientas marcan volumen 0",
      "En nichos B2B las mejores consultas tienen volumen bajo y alta intención; se encuentran en llamadas de ventas, no en herramientas de keywords.",
      ["seo", "buyer-persona"]),
    T("Contenido que citan las IAs: datos propios, definiciones y comparativas", "seo-aeo", "opinion", "contenido",
      "escribir contenido que los motores de IA usen como fuente",
      "Los modelos citan lo que es específico y verificable: cifras propias, definiciones claras y comparativas honestas; el contenido genérico desaparece.",
      ["aeo", "geo"]),
    T("Enlazado interno para sitios B2B: el SEO que casi nadie hace", "seo-aeo", "guia", "gm",
      "mejorar posiciones sin crear contenido nuevo",
      "Un buen enlazado interno entre pilares, satélites y páginas de servicio mueve posiciones más rápido que publicar más artículos.",
      ["seo", "landing-page"]),
    T("SEO técnico mínimo para un sitio B2B: lo que revisar antes de crear contenido", "seo-aeo", "checklist", "gm",
      "asegurarse de que el sitio no frena el SEO",
      "Antes de publicar más hay que confirmar que Google puede rastrear, indexar y entender el sitio; sin eso, el contenido no rinde.",
      ["seo", "serp"]),
    T("Share of voice en búsqueda: cómo compararte con tu competencia", "seo-aeo", "guia", "cmo",
      "saber si vas ganando o perdiendo visibilidad",
      "La visibilidad relativa frente a tres competidores dice más que la posición promedio; se mide por grupos de consultas de compra.",
      ["share-of-voice", "seo", "serp"]),

    # ───────── Paid media ─────────
    T("Paid media B2B orientado a pipeline: de optimizar clics a optimizar negocios", "paid-media", "marco", "cmo",
      "cambiar la forma de medir las campañas pagadas",
      "Una campaña B2B se juzga por las oportunidades que genera y su costo; optimizar CTR o CPL sin ver el CRM premia el tráfico equivocado.",
      ["roas", "romi", "cpl", "cac", "pipeline"], "roas-romi-roi", True),
    T("ROAS, ROMI y ROI: cuál usar para decidir el presupuesto", "paid-media", "comparativa", "cmo",
      "entender la diferencia entre indicadores de retorno",
      "El ROAS sirve para optimizar campañas; el ROMI, para defender el presupuesto, porque descuenta margen y todos los costos de marketing.",
      ["roas", "romi", "roi", "cac"], "roas-romi-roi"),
    T("LinkedIn Ads B2B con presupuesto acotado: segmentación que no quema dinero", "paid-media", "guia", "paid",
      "invertir en LinkedIn Ads sin desperdiciar",
      "Con poco presupuesto conviene una audiencia de cuentas bien definida y pocas campañas; segmentar por cargo amplio quema el presupuesto en días.",
      ["abm", "icp", "cpl", "ctr"], "roas-romi-roi"),
    T("Google Ads en nichos B2B de bajo volumen: cuándo sí y cuándo no", "paid-media", "opinion", "paid",
      "decidir si Google Ads vale la pena en un nicho",
      "Si nadie busca la solución, Google Ads no crea demanda; funciona cuando existe búsqueda con intención y el ticket soporta CPC altos.",
      ["cpc", "quality-score", "cpa"], "roas-romi-roi"),
    T("Atribuir paid media cuando el ciclo de venta dura meses", "paid-media", "marco", "ops",
      "medir el efecto real de las campañas en ventas largas",
      "Con ciclos largos la atribución de último clic subestima el paid; hay que conectar campañas con oportunidades en el CRM y mirar cohortes.",
      ["modelo-de-atribucion", "atribucion-multi-touch", "utm"], "roas-romi-roi"),
    T("Retargeting B2B que no persigue a todo el mundo", "paid-media", "guia", "paid",
      "usar retargeting con criterio",
      "El retargeting útil se segmenta por intención (páginas de precio, casos, demos) y por cuenta; perseguir a todo visitante solo encarece.",
      ["retargeting", "abm", "cpm"]),
    T("Cómo calcular un CAC realista para tus campañas", "paid-media", "guia", "ceo",
      "saber cuánto cuesta realmente un cliente",
      "El CAC real incluye sueldos, herramientas y agencia, no solo medios; sin eso, cualquier canal parece rentable.",
      ["cac", "ltv-cac", "payback-cac", "romi"], "roas-romi-roi"),
    T("Audiencias similares y listas de cuentas: cómo construirlas bien", "paid-media", "guia", "paid",
      "mejorar las audiencias de campañas B2B",
      "Una lookalike solo es tan buena como su lista semilla; usar clientes reales en lugar de todos los leads cambia el resultado.",
      ["audiencia-lookalike", "icp", "abm"]),
    T("Landing pages para campañas pagadas B2B: lo que cambia frente al sitio", "paid-media", "checklist", "paid",
      "mejorar la conversión de las campañas",
      "Una landing de campaña tiene un solo objetivo y repite la promesa del anuncio; mandar tráfico pagado al home desperdicia la mitad del presupuesto.",
      ["landing-page", "cro", "cta", "tasa-de-conversion"]),
    T("Presupuesto de paid media B2B: cómo repartirlo entre canales y etapas", "paid-media", "marco", "cmo",
      "armar el presupuesto anual de medios",
      "El presupuesto se reparte desde la meta de pipeline hacia atrás y se reserva un 15 % para pruebas; repartir por costumbre repite los errores del año anterior.",
      ["cac", "cpl", "pipeline"], "embudo-inverso"),

    # ───────── Contenido y email ─────────
    T("Contenido B2B que genera pipeline: del blog al caso de estudio", "contenido-email", "marco", "contenido",
      "planear contenido que ayude a vender",
      "El contenido que genera pipeline acompaña decisiones de compra concretas; un calendario de temas de tendencia produce tráfico sin negocio.",
      ["customer-journey", "buyer-persona", "nurturing"], "", True),
    T("Email marketing B2B: secuencias que la gente sí lee", "contenido-email", "guia", "gm",
      "mejorar las secuencias de correo",
      "Una secuencia que funciona es corta, escrita como una persona y con un siguiente paso claro por correo; los newsletters disfrazados no se leen.",
      ["nurturing", "cta", "ctr"]),
    T("Nurturing para ciclos de venta B2B de 6 a 12 meses", "contenido-email", "marco", "ops",
      "mantener vivos los leads que no están listos",
      "El nurturing de ciclo largo responde a las dudas de cada etapa de compra y sabe cuándo pasar el lead a ventas; enviar contenido por enviar quema la base.",
      ["nurturing", "ciclo-de-vida", "mql", "lead-scoring"]),
    T("Casos de estudio B2B que venden: estructura y cómo conseguir los datos", "contenido-email", "plantilla", "contenido",
      "escribir casos de estudio convincentes",
      "Un caso de estudio vende cuando muestra el antes y después con cifras y la decisión que tomó el cliente; los testimonios genéricos no convencen.",
      ["customer-journey", "buyer-persona"]),
    T("LinkedIn orgánico para directivos B2B: publicar sin convertirse en influencer", "contenido-email", "guia", "cmo",
      "construir presencia en LinkedIn con poco tiempo",
      "Para un directivo B2B basta una publicación útil por semana basada en su trabajo real; la constancia pesa más que el alcance.",
      ["inbound-marketing", "buyer-persona"]),
    T("Calendario editorial B2B: cómo planear un trimestre en una tarde", "contenido-email", "plantilla", "contenido",
      "organizar la producción de contenido",
      "Un calendario útil parte de 3 a 5 preguntas de compra por trimestre y de ahí deriva formatos; empezar por fechas y redes produce relleno.",
      ["buyer-persona", "customer-journey"]),
    T("Entregabilidad de email B2B: SPF, DKIM, DMARC y por qué tus correos llegan a spam", "contenido-email", "checklist", "ops",
      "evitar que los correos caigan en spam",
      "Sin autenticación correcta del dominio, ninguna mejora de copy importa; SPF, DKIM y DMARC son la base de cualquier programa de email.",
      ["nurturing"]),
    T("Reutilizar contenido B2B: un pilar, diez piezas", "contenido-email", "guia", "contenido",
      "producir más sin escribir más",
      "Un artículo pilar bien hecho alimenta correos, publicaciones, guiones de ventas y anuncios; producir siempre desde cero es el mayor desperdicio.",
      ["inbound-marketing"]),
    T("Newsletters B2B: cuándo valen la pena y cómo medirlas", "contenido-email", "opinion", "gm",
      "decidir si lanzar o mantener un newsletter",
      "Un newsletter vale la pena si tiene un punto de vista propio y una audiencia definida; medirlo solo por aperturas engaña desde la privacidad de Apple.",
      ["ctr", "nurturing"]),
    T("Copy B2B: escribir para quien decide y para quien evalúa", "contenido-email", "guia", "contenido",
      "escribir textos que convenzan a comités de compra",
      "En B2B compra un comité; el copy debe dar argumentos de negocio al que decide y respuestas técnicas al que evalúa, en la misma página.",
      ["buyer-persona", "cta"]),

    # ───────── Analítica y medición ─────────
    T("Medición de marketing B2B: del dato de campaña al ingreso en el CRM", "analitica", "marco", "cmo",
      "armar un sistema de medición de punta a punta",
      "Medir marketing B2B exige conectar campaña, contacto, oportunidad e ingreso; sin esa cadena, los reportes miden actividad y no resultados.",
      ["kpi", "modelo-de-atribucion", "utm", "romi", "pipeline"], "roas-romi-roi", True),
    T("Los KPIs de marketing B2B que sí le importan a dirección", "analitica", "checklist", "cmo",
      "elegir qué reportar a la dirección",
      "La dirección necesita cuatro números: pipeline creado, costo de adquisición, tasa de conversión a venta y retorno; el resto es para el equipo.",
      ["kpi", "cac", "romi", "pipeline", "win-rate"], "roas-romi-roi"),
    T("GA4 para marketing B2B: los eventos y conversiones que sí importan", "analitica", "guia", "gm",
      "configurar GA4 con sentido para B2B",
      "En B2B GA4 sirve para entender qué contenido acerca a la conversión; las ventas se miden en el CRM, no en GA4.",
      ["kpi", "tasa-de-conversion", "utm"]),
    T("UTMs sin caos: una convención que todo el equipo respeta", "analitica", "plantilla", "ops",
      "ordenar el etiquetado de campañas",
      "Una convención de UTMs de una página, con valores cerrados, evita que la mitad del tráfico termine como '(not set)' o duplicado.",
      ["utm", "modelo-de-atribucion"]),
    T("Modelos de atribución: first touch, last touch y multi-touch sin dogmas", "analitica", "comparativa", "cmo",
      "elegir un modelo de atribución",
      "Ningún modelo de atribución es la verdad; se usan dos en paralelo para responder preguntas distintas: qué inicia y qué cierra.",
      ["modelo-de-atribucion", "atribucion-first-touch", "atribucion-last-touch", "atribucion-multi-touch"]),
    T("Tablero de marketing para la junta semanal: qué poner y qué quitar", "analitica", "plantilla", "gm",
      "armar un tablero que se use",
      "Un tablero útil cabe en una pantalla y responde si vamos a llegar a la meta; si necesita explicación, tiene demasiado.",
      ["kpi", "pipeline", "forecast"]),
    T("Velocidad del pipeline: la métrica que conecta marketing con ingresos", "analitica", "guia", "ventas",
      "entender y mejorar la velocidad del pipeline",
      "La velocidad del pipeline muestra qué palanca mover: más oportunidades, mayor ticket, mejor cierre o ciclo más corto.",
      ["velocidad-del-pipeline", "win-rate", "pipeline"], "embudo-inverso"),
    T("LTV, CAC y payback: la salud financiera de tu marketing", "analitica", "guia", "ceo",
      "saber si el marketing es rentable",
      "La relación LTV/CAC y el periodo de recuperación dicen si se puede acelerar la inversión; crecer sin mirarlos es apostar.",
      ["ltv", "cac", "ltv-cac", "payback-cac", "churn"], "roas-romi-roi"),
    T("Calidad de datos en marketing: el problema que arruina cualquier reporte", "analitica", "errores", "ops",
      "entender por qué los reportes no cuadran",
      "La mayoría de los reportes que no cuadran tienen un problema de captura, no de análisis; se arregla en formularios y procesos.",
      ["crm", "utm"]),
    T("Cohortes en marketing B2B: medir lo que tarda meses en convertir", "analitica", "guia", "ops",
      "medir resultados con ciclos largos",
      "Comparar leads de un mes con ventas del mismo mes engaña; agrupar por cohorte de generación muestra la conversión real.",
      ["tasa-de-conversion", "pipeline", "mql"]),

    # ───────── Sitios web y conversión ─────────
    T("El sitio web B2B como sistema de captación: arquitectura, contenido y medición", "sitios-web", "marco", "cmo",
      "rediseñar el sitio para que genere leads",
      "Un sitio B2B se diseña desde las preguntas del comprador y los puntos de conversión, no desde el organigrama ni el catálogo de servicios.",
      ["landing-page", "cta", "cro", "tasa-de-conversion"], "", True),
    T("Anatomía de una landing B2B que convierte", "sitios-web", "plantilla", "gm",
      "estructurar una landing page",
      "Una landing B2B convierte cuando responde, en orden, qué es, para quién, por qué creerle y qué sigue; el diseño viene después.",
      ["landing-page", "cta", "cro"]),
    T("Formularios que convierten: integrar el sitio con el CRM sin perder datos", "sitios-web", "guia", "ops",
      "conectar formularios con el CRM",
      "Cada campo de más reduce conversiones y cada campo mal mapeado ensucia el CRM; menos campos y enriquecimiento posterior ganan.",
      ["crm", "tasa-de-conversion", "lead"]),
    T("CRO en B2B: experimentos que se pueden correr con poco tráfico", "sitios-web", "guia", "gm",
      "mejorar conversión sin tráfico masivo",
      "Con poco tráfico no hay pruebas A/B confiables; se mejora con entrevistas, grabaciones de sesión y cambios grandes medidos antes y después.",
      ["cro", "tasa-de-conversion", "tasa-de-rebote"]),
    T("Calculadoras y herramientas interactivas: el lead magnet que más convierte en B2B", "sitios-web", "opinion", "cmo",
      "decidir si invertir en herramientas interactivas",
      "Una calculadora útil entrega valor inmediato y califica al lead con sus propias respuestas; por eso convierte mejor que un PDF.",
      ["lead-magnet", "landing-page", "lead-scoring"], "embudo-inverso"),
    T("Páginas de precios B2B: mostrar, esconder o mostrar rangos", "sitios-web", "comparativa", "ceo",
      "decidir cómo comunicar precios",
      "Esconder todo el precio filtra mal; mostrar rangos o el modelo de cobro atrae a quien sí puede comprar y ahorra llamadas a ventas.",
      ["landing-page", "cta"]),
    T("Migrar el sitio sin perder posiciones: el checklist de SEO", "sitios-web", "checklist", "gm",
      "migrar de plataforma sin caer en Google",
      "Una migración sin mapa de redirecciones y monitoreo de las primeras semanas pierde meses de tráfico; el plan de SEO va antes que el diseño.",
      ["seo", "serp"]),
    T("Velocidad y experiencia en sitios B2B: lo que sí afecta la conversión", "sitios-web", "guia", "gm",
      "priorizar mejoras técnicas del sitio",
      "Las mejoras técnicas valen cuando afectan las páginas que convierten; optimizar todo el sitio por igual reparte el esfuerzo donde no rinde.",
      ["cro", "tasa-de-rebote"]),
    T("CTAs B2B: un siguiente paso por cada etapa de compra", "sitios-web", "marco", "contenido",
      "mejorar los llamados a la acción",
      "Pedir una demo a quien apenas investiga espanta; cada página necesita un CTA acorde a la etapa del lector.",
      ["cta", "customer-journey", "lead-magnet"]),
    T("WordPress, Webflow o headless para un sitio B2B: cómo decidir", "sitios-web", "comparativa", "ceo",
      "elegir la plataforma del sitio",
      "La plataforma correcta depende de quién va a mantener el sitio cada semana; la mejor tecnología sin quien la opere es la peor opción.",
      ["landing-page"]),

    # ───────── Liderazgo de equipos ─────────
    T("Liderar un equipo de marketing B2B: diseño, contenido, SDR y paid bajo un mismo sistema", "liderazgo", "marco", "cmo",
      "organizar un equipo de marketing multidisciplinario",
      "Un equipo de marketing B2B funciona cuando todos responden a la misma meta de pipeline; organizar por canales crea islas.",
      ["pipeline", "sdr", "kpi"], "embudo-inverso", True),
    T("Contratar al primer SDR y qué medirle en sus primeros 90 días", "liderazgo", "guia", "ventas",
      "incorporar un SDR con éxito",
      "Un SDR nuevo se mide primero por actividad y aprendizaje, luego por reuniones calificadas; exigir pipeline desde el mes uno quema talento.",
      ["sdr", "bdr", "sql"]),
    T("Rituales semanales para un equipo de marketing que trabaja con ventas", "liderazgo", "plantilla", "gm",
      "coordinar marketing y ventas cada semana",
      "Una junta semanal de 30 minutos sobre pipeline, con los mismos números para ambos equipos, evita la mayoría de los conflictos.",
      ["sla-marketing-ventas", "pipeline", "forecast"]),
    T("Del plan al sistema: la estrategia vale lo que vale su ejecución", "liderazgo", "opinion", "cmo",
      "convertir el plan anual en ejecución",
      "Un plan de marketing que no baja a responsables, fechas y tableros semanales es un documento; la ejecución se diseña igual que la estrategia.",
      ["kpi"]),
    T("Cómo presentar resultados de marketing a dirección", "liderazgo", "guia", "cmo",
      "ganar credibilidad con la dirección",
      "La dirección escucha pipeline, ingresos y costo; presentar impresiones y seguidores resta credibilidad a todo el área.",
      ["kpi", "romi", "pipeline"], "roas-romi-roi"),
    T("Agencia o equipo interno: qué tercerizar en marketing B2B", "liderazgo", "comparativa", "ceo",
      "decidir qué hacer en casa y qué contratar",
      "Lo estratégico y el conocimiento del cliente van en casa; la producción especializada y los picos de trabajo, afuera.",
      ["cac"]),
    T("Definir roles en un equipo de marketing pequeño", "liderazgo", "plantilla", "gm",
      "repartir responsabilidades con poca gente",
      "En equipos de 3 a 6 personas cada rol debe ser dueño de un número del embudo; los roles por tarea generan huecos.",
      ["kpi", "mql"]),
    T("OKRs para marketing B2B sin convertirlos en burocracia", "liderazgo", "guia", "cmo",
      "usar OKRs en marketing",
      "Tres objetivos por trimestre ligados al pipeline bastan; cuando hay 15 resultados clave, ninguno es prioridad.",
      ["kpi", "pipeline"]),
    T("Onboarding de marketing: los primeros 30 días de alguien nuevo", "liderazgo", "checklist", "gm",
      "incorporar a una persona nueva al equipo",
      "El onboarding de marketing incluye escuchar llamadas de ventas y entender el CRM; sin eso, la persona produce sin contexto.",
      ["crm", "buyer-persona"]),
    T("Alinear marketing y ventas: el SLA que evita las peleas", "liderazgo", "plantilla", "ventas",
      "acordar compromisos entre marketing y ventas",
      "Un SLA con volumen de leads, tiempo de respuesta y criterios de rechazo, revisado cada mes, convierte la discusión en datos.",
      ["sla-marketing-ventas", "mql", "sql", "sal"], "embudo-inverso"),

    # ───────── IA aplicada ─────────
    T("IA aplicada a marketing B2B sin humo: casos que sí ahorran tiempo", "ia-aplicada", "marco", "cmo",
      "saber dónde usar IA en marketing",
      "La IA rinde en tareas repetitivas con criterio claro: clasificar, resumir, redactar borradores y enriquecer datos; no sustituye la estrategia.",
      ["revops", "lead-scoring", "crm"], "", True),
    T("Modelos locales vs. APIs de IA para marketing: costos, privacidad y calidad", "ia-aplicada", "comparativa", "ceo",
      "decidir dónde correr la IA",
      "Los modelos locales ganan en privacidad y costo fijo; las APIs, en calidad y rapidez para empezar. La decisión depende de volumen y datos sensibles.",
      []),
    T("Enriquecer y limpiar el CRM con IA: qué automatizar y qué revisar a mano", "ia-aplicada", "guia", "ops",
      "usar IA para mejorar datos del CRM",
      "La IA clasifica industrias y normaliza cargos muy bien; las decisiones de fusión y propiedad del cliente deben quedar en manos humanas.",
      ["crm", "icp"]),
    T("Escribir con IA sin sonar a IA: un flujo editorial para marketing B2B", "ia-aplicada", "guia", "contenido",
      "producir contenido con IA manteniendo calidad",
      "La IA hace buenos borradores cuando recibe tesis, lector y ejemplos; sin brief produce texto genérico que cualquier lector detecta.",
      ["inbound-marketing"]),
    T("Lead scoring con IA: cuándo supera a las reglas y cuándo no", "ia-aplicada", "comparativa", "ops",
      "evaluar scoring predictivo",
      "Un modelo predictivo necesita cientos de ventas cerradas para aprender; con menos datos, las reglas simples ganan.",
      ["lead-scoring", "mql"]),
    T("Resumir llamadas de ventas con IA para alimentar marketing", "ia-aplicada", "guia", "ventas",
      "aprovechar las llamadas de ventas",
      "Las llamadas de ventas son la mejor fuente de objeciones y lenguaje del cliente; resumirlas con IA convierte ese conocimiento en contenido y mensajes.",
      ["buyer-persona", "customer-journey"]),
    T("Agentes de IA en marketing: qué tareas delegar hoy", "ia-aplicada", "opinion", "cmo",
      "entender qué pueden hacer los agentes",
      "Los agentes funcionan en tareas acotadas con verificación; dejarlos publicar o escribir al cliente sin revisión es un riesgo de marca.",
      []),
    T("Prompts para marketing B2B: la estructura que da buenos resultados", "ia-aplicada", "plantilla", "contenido",
      "mejorar los resultados al usar IA",
      "Un buen prompt define rol, lector, objetivo, restricciones y formato; pedir 'un artículo sobre X' da un artículo como cualquier otro.",
      []),
    T("Visibilidad en motores de IA: lo que un equipo de marketing puede controlar", "ia-aplicada", "marco", "cmo",
      "influir en cómo las IAs mencionan a la marca",
      "La marca aparece en respuestas de IA cuando hay contenido propio claro, menciones en fuentes confiables y datos consistentes en la web.",
      ["aeo", "geo", "share-of-voice"]),
    T("Gobernanza de IA en marketing: reglas para usarla sin riesgos", "ia-aplicada", "checklist", "cmo",
      "establecer reglas de uso de IA en el equipo",
      "Unas reglas de una página sobre datos permitidos, revisión humana y herramientas aprobadas evitan fugas de información y errores públicos.",
      []),
]

assert len(TOPICS) == 90, len(TOPICS)
